name: Build

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore .\MyTime.sln

      - name: Build
        run: dotnet build .\MyTime.sln --configuration Release --no-restore

      - name: Publish app
        run: dotnet publish .\src\MyTime\MyTime.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=false

      - name: Upload publish artifact
        uses: actions/upload-artifact@v5
        with:
          name: MyTime-publish
          path: src/MyTime/bin/Release/net10.0-windows/win-x64/publish
          if-no-files-found: error
